"""add user_chats_title

Revision ID: 5e742a0825b4
Revises: 7e6dd0e90295
Create Date: 2026-01-17 19:11:23.020332

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e742a0825b4'
down_revision: Union[str, Sequence[str], None] = '7e6dd0e90295'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_chats', sa.Column('title', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_chats', 'title')
    # ### end Alembic commands ###
