"""update user_chat_schema

Revision ID: 86e5c2f9c393
Revises: 9319ba93a35b
Create Date: 2026-01-18 13:51:46.961499

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86e5c2f9c393'
down_revision: Union[str, Sequence[str], None] = '9319ba93a35b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_user_chats_user_chat', 'user_chats', ['user_id', 'chat_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_user_chats_user_chat', 'user_chats', type_='unique')
    # ### end Alembic commands ###
