"""Add link in chat

Revision ID: 905e93f6e066
Revises: 9e1bcb5df1f9
Create Date: 2026-01-17 14:16:15.559162

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '905e93f6e066'
down_revision: Union[str, Sequence[str], None] = '9e1bcb5df1f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('link_in_chat', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'link_in_chat')
    # ### end Alembic commands ###
